install:
	# installing...
	pip install --upgrade pip && pip install -r requirements.txt
format:
	# formating...
lint:
	# linging... flake8
test:
	# testing...
deploy:
	# deploying...
all: install lint test deploy
